name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Run dependencies
        run: |
          bundle install

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install Sass
        run: npm install -g sass

      - name: Build CSS
        run: rails css:install:bootstrap && yarn build:css      
      
      - name: Run tests
        run: |
          bundle exec rake

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

  deploy_on_googles_app_engine:
    name: Deploy
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check pwd
        run: ls -la
      - uses: 73h/gae-app-yaml-replace-env-variables@v0.1
        working-directory: ${{ github.workspace }}/tmp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        with:
          app_yaml_path: "app.yaml"
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_JSON }}'
      - uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app.yaml'
          promote: true
          version: 'v1'        