name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Run dependencies
        run: |
          bundle install
      
      - name: Run tests
        uses: actions/checkout@v3
        uses: isbang/compose-action@v1.4.1
        run: |
          bundle exec rake