name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Run dependencies
        run: |
          bundle install

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install Sass
        run: npm install -g sass

      - name: Build CSS
        run: yarn build:css      
      
      - name: Run tests
        run: |
          bundle exec rake

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down    